AWSTemplateFormatVersion: 2010-09-09

Parameters:
  OwnerTag:
    Description: Your initial
    Type: String
    Default: ldj

  OpenSearchDomainEndpoint:
    Description: 생성된 Opensearch의 도메인 엔드포인트
    Type: String
    Default: https://search-ldj-opensearch-test-domain-274gdajy6lcu5uu2r7byb625rq.ap-northeast-1.es.amazonaws.com

  OpenSearchPipeRoleARN:
    Description: 생성된 role의 arn
    Type: String
    Default: arn:aws:iam::851725230407:role/

  LogCentralBucketName:
    Description: 중앙화 버킷의 이름
    Type: String
    Default: log-central-ldj-

  anfwBucketPrefix:
    Description: anfw의 prefix
    Type: String
    Default: networkfirewall/
  
  anfwIndexName:
    Description: anfw의 index명
    Type: String
    Default: anfw


Resources:
  OpenSearchANFWPipe:
    DependsOn: [PipeLogGroup]
    Type: AWS::OSIS::Pipeline
    Properties:
      BufferOptions: 
         PersistentBufferEnabled: false
      #EncryptionAtRestOptions:  #암호화 여부
      #  EncryptionAtRestOptions
      LogPublishingOptions: 
          CloudWatchLogDestination: 
            LogGroup: !Sub "/aws/vendedlogs/OpenSearchIngestion/${OwnerTag}anwf/audit-logs"
          IsLoggingEnabled: true
      MaxUnits: 2
      MinUnits: 1
      PipelineConfigurationBody: !Sub |
        version: "2"
        log-pipeline:
          source:
            s3:
              codec:
                newline:  # Other options "json", "csv", "parquet"
              # Provide compression property, can be "none", "gzip", or "automatic"
              
              compression: "gzip"       #or automatic
              aws:
                region: "${AWS::Region}"
        
                #생성해준 pipeline의 role
                sts_role_arn: "${OpenSearchPipeRoleARN}"
              acknowledgments: true
              scan: # Define scan start and end times at scan level. Applicable for all buckets.
                # start_time: 2023-01-01T18:00:00
                # end_time: 2023-08-31T18:00:00
                # Alternatively scan can be defined as range as well. PT4H would scan all files created in the last 4 Hours.
                # Examples: "PT4H" or "PT30M" or "PT100S" or "P3D" or "P1W"
                range: "PT10H" #4시간동안 생성된 파일 스캔 
                buckets:
                  - bucket:
                      name: "${LogCentralBucketName}"
                      filter:
                        include_prefix: 
                          - "${anfwBucketPrefix}"
              delete_s3_objects_on_read: false
          processor:
            - parse_json:
                pointer: "message/event"
          sink:
            - opensearch:
                hosts:
                  ["${OpenSearchDomainEndpoint}"]
                index: "netfireproc12"
                aws:
                  sts_role_arn: "${OpenSearchPipeRoleARN}"
                  region: "${AWS::Region}"
                  serverless: false
      PipelineName: !Sub "${OwnerTag}-anwfpipe"
      Tags: 
        -
          Key: owner
          Value: !Ref OwnerTag
  PipeLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      #DataProtectionPolicy: Json
      #KmsKeyId: String
      #LogGroupClass: String # Infrequent Access로 가능
      LogGroupName: !Sub "/aws/vendedlogs/OpenSearchIngestion/${OwnerTag}anwf/audit-logs"
      RetentionInDays: 3   #유지 기간
      Tags:
        -
          Key: owner
          Value: !Ref OwnerTag
