version: "2"
log-pipeline:
  source:
    s3:
      codec:
        json:  # Other options "json", "csv", "parquet"
      # Provide compression property, can be "none", "gzip", or "automatic"
      
      compression: "gzip"       #or automatic
      aws:
        region: "ap-northeast-1"

        #생성해준 pipeline의 role
        sts_role_arn: "arn:aws:iam::851725230407:role/opensearch-s3-pipe-role"
      acknowledgments: true
      scan:
        range: "PT10H" #4시간동안 생성된 파일 스캔 
        buckets:
          - bucket:
              name: "log-central-ldj-k9dbddjg"
              filter:
                include_prefix:   #가져올 버킷의 prefix
                  - config/
      delete_s3_objects_on_read: false
  sink:
    - opensearch:
        #생성된 OpenSearch Service domain endpoint
        hosts: ["https://search-ldj-opensearch-test-domain-274gdajy6lcu5uu2r7byb625rq.ap-northeast-1.es.amazonaws.com"]

        #넣어줄 인덱스의 이름
        index: "config" 
        aws:
          sts_role_arn: "arn:aws:iam::851725230407:role/opensearch-s3-pipe-role"
          region: "ap-northeast-1"
          serverless: false
